# Generated by Django 3.2.12 on 2022-06-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 't_web_slide',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_web_slide_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_website', models.CharField(max_length=200)),
                ('ip_production', models.CharField(max_length=100)),
                ('ip_development', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 't_website_name',
            },
        ),
    ]
