# Generated by Django 3.2.12 on 2022-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitename',
            name='dominio',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
