# Generated by Django 3.2.12 on 2022-08-25 16:52

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0014_alter_tzona_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('abreviacion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 't_componente_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GisBaseZonasAmbitosVertices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=32719)),
                ('etiqueta', models.CharField(blank=True, max_length=5, null=True)),
                ('codigo_zre', models.CharField(blank=True, max_length=15, null=True)),
                ('utm_este', models.FloatField(blank=True, null=True)),
                ('utm_norte', models.FloatField(blank=True, null=True)),
                ('vertice', models.CharField(blank=True, max_length=10, null=True)),
                ('lado', models.CharField(blank=True, max_length=15, null=True)),
                ('angulo', models.CharField(blank=True, max_length=15, null=True)),
                ('este', models.FloatField(blank=True, null=True)),
                ('norte', models.FloatField(blank=True, null=True)),
                ('distancia', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': '"zre41"."gis_base_zonas_ambitos_vertices"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GisBaseZonasZreV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=3, null=True, srid=32719)),
                ('codigo_zre', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': '"zre41"."gis_base_zonas_zre_v2"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GisBaseZonasZreVertices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=32719)),
                ('etiqueta', models.CharField(blank=True, max_length=5, null=True)),
                ('codigo_zre', models.CharField(blank=True, max_length=15, null=True)),
                ('utm_este', models.FloatField(blank=True, null=True)),
                ('utm_norte', models.FloatField(blank=True, null=True)),
                ('vertice', models.CharField(blank=True, max_length=10, null=True)),
                ('lado', models.CharField(blank=True, max_length=15, null=True)),
                ('angulo', models.CharField(blank=True, max_length=15, null=True)),
                ('este', models.FloatField(blank=True, null=True)),
                ('norte', models.FloatField(blank=True, null=True)),
                ('distancia', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': '"zre41"."gis_base_zonas_zre_vertices"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 't_plan_etapa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('objetivo', models.TextField()),
                ('unidad_organizacional_id', models.IntegerField()),
            ],
            options={
                'db_table': 't_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_doc_identidad', models.CharField(max_length=50)),
                ('nro_doc_identidad', models.CharField(max_length=10)),
                ('organizacion', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=50)),
                ('tipo_observacion', models.CharField(max_length=20)),
                ('documento_observacion', models.CharField(max_length=20)),
                ('observaciones', models.TextField(max_length=500)),
                ('archivo_adjunto', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=200)),
                ('num_users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeodataZonasPeligroMuyAltoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('wms', models.CharField(blank=True, max_length=200, null=True)),
                ('style', models.CharField(blank=True, max_length=200, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('zona_type', models.CharField(blank=True, max_length=200, null=True)),
                ('geometry_type', models.CharField(blank=True, max_length=200, null=True)),
                ('componente', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbails', models.CharField(blank=True, max_length=200, null=True)),
                ('kml_link', models.CharField(blank=True, max_length=200, null=True)),
                ('shp_link', models.CharField(blank=True, max_length=200, null=True)),
                ('geojson_link', models.CharField(blank=True, max_length=200, null=True)),
                ('wms_link', models.CharField(blank=True, max_length=200, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_geodata_zonas_peligro_muy_alto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('image2', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_plan', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(default=None, max_length=250, null=True)),
                ('estado_plan_id', models.IntegerField()),
                ('url_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('url_reglamento', models.CharField(blank=True, max_length=200, null=True)),
                ('url_evar_cenepred', models.CharField(blank=True, max_length=200, null=True)),
                ('elaboracion_fecha_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('elaboracion_fecha_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('consulta_fecha_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('consulta_fecha_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('lev_observaciones', models.CharField(blank=True, max_length=20, null=True)),
                ('aprobacion_fecha', models.CharField(blank=True, max_length=20, null=True)),
                ('aprobacion_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_plan_id', models.IntegerField()),
                ('provincia_id', models.IntegerField()),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='world.tzona')),
            ],
            options={
                'db_table': 't_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ViewGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaCaracterizacionGRDAnalisisVulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '11:Zona C2:10:Caracterizacion GRD Analisis Vulnerabilidad',
                'db_table': 't_zona_carac_grd_anali_vulnera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaCaracterizacionGRDDeterminacionPeligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '10:Zona C2:09:Caracterizacion GRD Determinacion Peligro',
                'db_table': 't_zona_carac_grd_determ_peligro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaCaracterizacionLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '09:Zona C2:08:Caracterizacion Legal',
                'db_table': 't_zona_caracterizacion_legal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaCaracterizacionSocioeconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '08:Zona C2:07:Caracterizacion Socioeconomica',
                'db_table': 't_zona_caracterizacion_socioeconomica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaConsideracionesGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '01:Zona C1:01:Considera Generales',
                'db_table': 't_zona_consideraciones_generales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaDelimitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '06:Zona C1:05:Delimitacion',
                'db_table': 't_zona_delimitacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaDensidadPoblacionalTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('agno', models.IntegerField(default=0, null=True)),
                ('aoi', models.CharField(max_length=250, null=True)),
                ('tipo_densidad', models.CharField(max_length=250, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nro_habitantes', models.IntegerField(default=0, null=True)),
                ('superficie_aoi', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('fuente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_densidad_poblacional_zona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaJustificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '04:Zona C1:03:Justificacion',
                'db_table': 't_zona_justificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaMetodologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '05:Zona C1:04:Metodologia',
                'db_table': 't_zona_metodologia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaNivelInstruccionTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('agno', models.IntegerField(default=0, null=True)),
                ('rango', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('fuente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_nivel_instruccion_zona_tabla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaObjetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '03:Zona C1:02:Objetivos',
                'db_table': 't_zona_objetivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaPlaneamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '07:Zona C1:06:Planeamiento',
                'db_table': 't_zona_planeamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaPoblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('agno', models.IntegerField(default=0, null=True)),
                ('ge_0_5', models.IntegerField(default=0, null=True)),
                ('ge_6_12', models.IntegerField(default=0, null=True)),
                ('ge_13_18', models.IntegerField(default=0, null=True)),
                ('ge_19_30', models.IntegerField(default=0, null=True)),
                ('ge_31_54', models.IntegerField(default=0, null=True)),
                ('ge_55_65', models.IntegerField(default=0, null=True)),
                ('ge_66_mas', models.IntegerField(default=0, null=True)),
                ('discapacitados', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 't_poblacion_zona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaPoblacionTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('agno', models.IntegerField()),
                ('rango', models.CharField(max_length=50)),
                ('valor', models.IntegerField(default=0, null=True)),
                ('fuente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_poblacion_zona_tabla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZonaPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '00:Zona 00:00:Presentacion',
                'db_table': 't_zona_presentacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zony2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'zre41"."zony2',
            },
        ),
        migrations.CreateModel(
            name='PlanMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('mapa_tipo_id', models.IntegerField()),
                ('planEtapa_id', models.IntegerField()),
                ('fecha_updated', models.DateField(blank=True, default=datetime.date.today)),
                ('componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zonas.componente')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapas', to='zonas.plan')),
                ('plan_etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zonas.planetapa')),
            ],
            options={
                'db_table': 't_plan_mapa',
                'managed': True,
            },
        ),
    ]
