# Generated by Django 3.2.12 on 2022-06-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('image2', models.CharField(max_length=200)),
                ('codigo_plan', models.CharField(max_length=200)),
                ('estado_plan_id', models.IntegerField()),
                ('url_documento', models.CharField(max_length=200)),
                ('url_reglamento', models.CharField(max_length=200)),
                ('url_evar_cenepred', models.CharField(max_length=200)),
                ('elaboracion_fecha_inicio', models.DateTimeField()),
                ('elaboracion_fecha_fin', models.DateTimeField()),
                ('consulta_fecha_inicio', models.DateTimeField()),
                ('consulta_fecha_fin', models.DateTimeField()),
                ('lev_observaciones', models.DateTimeField()),
                ('aprobacion_fecha', models.DateTimeField()),
                ('aprobacion_documento', models.IntegerField()),
                ('prioridad', models.CharField(max_length=200)),
                ('tipo_plan_id', models.IntegerField()),
                ('provincia_id', models.IntegerField()),
                ('zona_id', models.IntegerField()),
            ],
            options={
                'db_table': 't_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zony2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'zre41"."zony2',
            },
        ),
    ]
