# Generated by Django 3.2.12 on 2022-08-25 18:00

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeodataZonasPeligroMuyAltoItem',
            new_name='GeodataZonasPorPeligroMuyAltoItem',
        ),
        migrations.AlterModelTable(
            name='geodatazonasporpeligromuyaltoitem',
            table='t_geodata_zonas_x_peligro_muy_alto',
        ),
        migrations.CreateModel(
            name='GeodataZonasPorPeligroMuyAltoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('wms', models.CharField(blank=True, max_length=200, null=True)),
                ('style', models.CharField(blank=True, max_length=200, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('zona_type', models.CharField(blank=True, max_length=200, null=True)),
                ('geometry_type', models.CharField(blank=True, max_length=200, null=True)),
                ('componente', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbails', models.CharField(blank=True, max_length=200, null=True)),
                ('kml_link', models.CharField(blank=True, max_length=200, null=True)),
                ('shp_link', models.CharField(blank=True, max_length=200, null=True)),
                ('geojson_link', models.CharField(blank=True, max_length=200, null=True)),
                ('wms_link', models.CharField(blank=True, max_length=200, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_geodata_zonas_x_peligro_muy_alto',
                'managed': True,
            },
        ),
    ]
