# Generated by Django 3.2.12 on 2022-08-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_auto_20220825_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geodatazonasporpeligromuyaltoitem',
            old_name='enable',
            new_name='enabled',
        ),
    ]
