# Generated by Django 3.2.12 on 2022-06-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_auto_20220620_0821'),
        ('zonas', '0002_alter_plan_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='zona_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.tzona'),
        ),
    ]
