# Generated by Django 3.2.12 on 2022-06-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0003_auto_20220620_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 't_componente_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 't_plan_etapa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('mapa_tipo_id', models.IntegerField()),
                ('planEtapa_id', models.IntegerField()),
            ],
            options={
                'db_table': 't_plan_mapa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('objetivo', models.TextField()),
                ('unidad_organizacional_id', models.IntegerField()),
            ],
            options={
                'db_table': 't_proyecto',
                'managed': False,
            },
        ),
    ]
