# Generated by Django 3.2.12 on 2022-08-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0003_rename_enable_geodatazonasporpeligromuyaltoitem_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geodatazonasporpeligromuyaltoitem',
            old_name='thumbails',
            new_name='thumbnails',
        ),
    ]
