# Generated by Django 3.2.12 on 2022-08-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0004_rename_thumbails_geodatazonasporpeligromuyaltoitem_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodatazonasporpeligromuyaltoitem',
            name='geojson_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='geodatazonasporpeligromuyaltoitem',
            name='kml_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='geodatazonasporpeligromuyaltoitem',
            name='shp_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='geodatazonasporpeligromuyaltoitem',
            name='wms_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
