# Generated by Django 3.2.12 on 2022-06-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0004_componente_planetapa_planmapa_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='aprobacion_fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='consulta_fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='consulta_fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='elaboracion_fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='elaboracion_fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='lev_observaciones',
            field=models.DateField(),
        ),
    ]
