# Generated by Django 3.2.12 on 2022-06-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0005_auto_20220628_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planetapa',
            options={},
        ),
    ]
