# Generated by Django 3.2.12 on 2022-08-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0005_auto_20220829_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeodataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('componente', models.CharField(blank=True, max_length=200, null=True)),
                ('etapa', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_zona', models.CharField(blank=True, max_length=200, null=True)),
                ('style', models.CharField(blank=True, max_length=200, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('geometry_type', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnails', models.CharField(blank=True, max_length=200, null=True)),
                ('kml_link', models.CharField(blank=True, max_length=250, null=True)),
                ('shp_link', models.CharField(blank=True, max_length=250, null=True)),
                ('geojson_link', models.CharField(blank=True, max_length=250, null=True)),
                ('wms', models.CharField(blank=True, max_length=200, null=True)),
                ('wms_link', models.CharField(blank=True, max_length=250, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('sistema_geodesico', models.CharField(blank=True, default='WGS84', max_length=50, null=True)),
                ('sistema_geodesico_zona', models.CharField(blank=True, default='19S', max_length=50, null=True)),
            ],
            options={
                'db_table': 't_geodata_item',
                'managed': True,
            },
        ),
    ]
