# Generated by Django 3.2.12 on 2022-08-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0006_geodataitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataitem',
            name='tipo_zona',
            field=models.CharField(choices=[('apma', 'Area de Peligro Muy Alto'), ('acpa', 'Area de Conservación y Protección Ambiental')], max_length=4),
        ),
    ]
