# Generated by Django 3.2.12 on 2022-06-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0006_alter_planetapa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planetapa',
            options={'managed': False},
        ),
    ]
