# Generated by Django 3.2.12 on 2022-06-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0007_alter_planetapa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
