# Generated by Django 3.2.12 on 2022-08-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0007_alter_geodataitem_tipo_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodatazonasporpeligromuyaltoitem',
            name='componente',
        ),
    ]
