# Generated by Django 3.2.12 on 2022-08-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0009_remove_geodatazonasporpeligromuyaltoitem_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodatazonasporpeligromuyaltoitem',
            name='componente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zonas.componente'),
        ),
    ]
