# Generated by Django 3.2.12 on 2022-08-31 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0010_geodatazonasporpeligromuyaltoitem_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataitem',
            name='componente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zonas.componente'),
        ),
        migrations.AlterField(
            model_name='geodatazonasporpeligromuyaltoitem',
            name='componente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
