# Generated by Django 3.2.12 on 2022-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0010_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_doc_identidad', models.CharField(max_length=50)),
                ('nro_doc_identidad', models.CharField(max_length=10)),
                ('organizacion', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=50)),
                ('tipo_observacion', models.CharField(max_length=20)),
                ('documento_observacion', models.CharField(max_length=20)),
                ('observaciones', models.TextField(max_length=500)),
                ('archivo_adjunto', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
