# Generated by Django 3.2.12 on 2022-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0011_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='aprobacion_documento',
            field=models.CharField(max_length=200),
        ),
    ]
