# Generated by Django 3.2.12 on 2022-08-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0012_alter_geodataitem_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodataitem',
            name='geometry_type',
            field=models.CharField(choices=[('point', 'Punto'), ('polyline', 'Polilínea'), ('polygon', 'Polígono'), ('raster', 'Ráster')], max_length=15),
        ),
    ]
