# Generated by Django 3.2.12 on 2022-07-07 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_auto_20220620_0821'),
        ('zonas', '0012_alter_plan_aprobacion_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.tzona'),
        ),
    ]
