# Generated by Django 3.2.12 on 2022-07-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0014_alter_tzona_options'),
        ('zonas', '0013_alter_plan_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='world.tzona'),
        ),
    ]
