# Generated by Django 3.2.12 on 2022-07-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0014_alter_plan_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaPoblacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ge_0_5', models.IntegerField(null=True)),
                ('ge_6_12', models.IntegerField(null=True)),
                ('ge_13_18', models.IntegerField(null=True)),
                ('ge_19_30', models.IntegerField(null=True)),
                ('ge_31_54', models.IntegerField(null=True)),
                ('ge_55_65', models.IntegerField(null=True)),
                ('ge_66_mas', models.IntegerField(null=True)),
                ('discapacitados', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 't_poblacion_zona',
                'managed': True,
            },
        ),
    ]
