# Generated by Django 3.2.12 on 2022-07-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0015_zonapoblacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonapoblacion',
            name='agno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zonapoblacion',
            name='codigo_zona',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
