# Generated by Django 3.2.12 on 2022-07-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0016_auto_20220719_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonapoblacion',
            name='agno',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonapoblacion',
            name='discapacitados',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonapoblacion',
            name='ge_0_5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonapoblacion',
            name='ge_13_18',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonapoblacion',
            name='ge_19_30',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonapoblacion',
            name='ge_31_54',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonapoblacion',
            name='ge_55_65',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonapoblacion',
            name='ge_66_mas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonapoblacion',
            name='ge_6_12',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zonapoblacion',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
