# Generated by Django 3.2.12 on 2022-07-19 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0018_viewgraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 13, 59, 57, 934504, tzinfo=utc)),
        ),
    ]
