# Generated by Django 3.2.12 on 2022-07-19 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0019_alter_viewgraph_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=200)),
                ('num_users', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 14, 16, 25, 817565, tzinfo=utc)),
        ),
    ]
