# Generated by Django 3.2.12 on 2022-07-19 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0020_auto_20220719_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaPoblacionTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('agno', models.IntegerField()),
                ('rango', models.CharField(max_length=50)),
                ('valor', models.IntegerField(default=0, null=True)),
                ('fuente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_poblacion_zona_tabla',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 16, 35, 19, 295023, tzinfo=utc)),
        ),
    ]
