# Generated by Django 3.2.12 on 2022-07-19 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0021_auto_20220719_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaNivelInstruccionTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('agno', models.IntegerField(default=0, null=True)),
                ('rango', models.CharField(max_length=50)),
                ('valor', models.IntegerField(default=0, null=True)),
                ('fuente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_nivel_instruccion_zona_tabla',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 21, 5, 46, 326441, tzinfo=utc)),
        ),
    ]
