# Generated by Django 3.2.12 on 2022-07-19 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0022_auto_20220719_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 21, 6, 52, 597870, tzinfo=utc)),
        ),
    ]
