# Generated by Django 3.2.12 on 2022-07-20 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0023_alter_viewgraph_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaDensidadPoblacionalTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('agno', models.IntegerField(default=0, null=True)),
                ('aoi', models.CharField(default=0, max_length=150, null=True)),
                ('tipo_densidad', models.IntegerField(default=0, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('nro_habitantes', models.IntegerField(default=0, null=True)),
                ('superficie_aoi', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('fuente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_densidad_poblacional_zona',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 15, 12, 34, 296524, tzinfo=utc)),
        ),
    ]
