# Generated by Django 3.2.12 on 2022-07-20 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0024_auto_20220720_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 15, 33, 55, 61964, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='zonadensidadpoblacionaltabla',
            name='aoi',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
