# Generated by Django 3.2.12 on 2022-07-20 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0025_auto_20220720_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 15, 35, 20, 649345, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='zonadensidadpoblacionaltabla',
            name='tipo_densidad',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
