# Generated by Django 3.2.12 on 2022-07-20 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0026_auto_20220720_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 16, 24, 54, 292662, tzinfo=utc)),
        ),
    ]
