# Generated by Django 3.2.12 on 2022-07-20 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0027_alter_viewgraph_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 18, 59, 19, 102760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='zonanivelinstrucciontabla',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
