# Generated by Django 3.2.12 on 2022-07-26 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0028_auto_20220720_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 't_zona_presentacion',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='viewgraph',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
