# Generated by Django 3.2.12 on 2022-07-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0029_auto_20220726_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonapresentacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
