# Generated by Django 3.2.12 on 2022-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0033_zonajustificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaMetodologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '05:Zona C1:04:Metodologia',
                'db_table': 't_zona_metodologia',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='zonaconsideracionesgenerales',
            options={'managed': True, 'verbose_name_plural': '01:Zona C1:01:Considera Generales'},
        ),
        migrations.AlterModelOptions(
            name='zonajustificacion',
            options={'managed': True, 'verbose_name_plural': '04:Zona C1:03:Justificacion'},
        ),
        migrations.AlterModelOptions(
            name='zonaobjetivos',
            options={'managed': True, 'verbose_name_plural': '03:Zona C1:02:Objetivos'},
        ),
        migrations.AlterModelOptions(
            name='zonapresentacion',
            options={'managed': True, 'verbose_name_plural': '00:Zona 00:00:Presentacion'},
        ),
    ]
