# Generated by Django 3.2.12 on 2022-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0034_auto_20220801_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaDelimitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '06:Zona C1:05:Delimitacion',
                'db_table': 't_zona_delimitacion',
                'managed': True,
            },
        ),
    ]
