# Generated by Django 3.2.12 on 2022-08-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0035_zonadelimitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaPlaneamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '07:Zona C1:06:Planeamiento',
                'db_table': 't_zona_planeamiento',
                'managed': True,
            },
        ),
    ]
