# Generated by Django 3.2.12 on 2022-08-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0037_zonacaracterizaciongrdanalisisvulnerabilidad_zonacaracterizaciongrddeterminacionpeligro_zonacaracter'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ZonaCaracterizacionLegal',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
        #         ('descripcion', models.TextField(blank=True, null=True)),
        #     ],
        #     options={
        #         'verbose_name_plural': '09:Zona C2:08:Caracterizacion Legal',
        #         'db_table': 't_zona_caracterizacion_legal',
        #         'managed': True,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ZonaCaracterizacionSocioeconomica',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
        #         ('descripcion', models.TextField(blank=True, null=True)),
        #     ],
        #     options={
        #         'verbose_name_plural': '08:Zona C2:07:Caracterizacion Socioeconomica',
        #         'db_table': 't_zona_caracterizacion_socioeconomica',
        #         'managed': True,
        #     },
        # ),
        migrations.AlterModelTable(
            name='zonacaracterizaciongrdanalisisvulnerabilidad',
            table='t_zona_carac_grd_anali_vulnera',
        ),
        migrations.AlterModelTable(
            name='zonacaracterizaciongrddeterminacionpeligro',
            table='t_zona_carac_grd_determ_peligro',
        ),
    ]
