# Generated by Django 3.2.12 on 2022-08-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0038_auto_20220803_1926'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ZonaCaracterizacionLegal',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
        #         ('descripcion', models.TextField(blank=True, null=True)),
        #     ],
        #     options={
        #         'verbose_name_plural': '09:Zona C2:08:Caracterizacion Legal',
        #         'db_table': 't_zona_caracterizacion_legal',
        #         'managed': True,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ZonaCaracterizacionSocioeconomica',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
        #         ('descripcion', models.TextField(blank=True, null=True)),
        #     ],
        #     options={
        #         'verbose_name_plural': '08:Zona C2:07:Caracterizacion Socioeconomica',
        #         'db_table': 't_zona_caracterizacion_socioeconomica',
        #         'managed': True,
        #     },
        # ),
        migrations.AlterField(
            model_name='plan',
            name='aprobacion_documento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='aprobacion_fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='codigo_plan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='consulta_fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='consulta_fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='elaboracion_fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='elaboracion_fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='lev_observaciones',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='prioridad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='url_documento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='url_evar_cenepred',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='url_reglamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
