# Generated by Django 3.2.12 on 2022-08-10 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0044_auto_20220810_1257'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ZonaCaracterizacionLegal',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
        #         ('descripcion', models.TextField(blank=True, null=True)),
        #     ],
        #     options={
        #         'verbose_name_plural': '09:Zona C2:08:Caracterizacion Legal',
        #         'db_table': 't_zona_caracterizacion_legal',
        #         'managed': True,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ZonaCaracterizacionSocioeconomica',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('codigo_zona', models.CharField(blank=True, max_length=50, null=True)),
        #         ('descripcion', models.TextField(blank=True, null=True)),
        #     ],
        #     options={
        #         'verbose_name_plural': '08:Zona C2:07:Caracterizacion Socioeconomica',
        #         'db_table': 't_zona_caracterizacion_socioeconomica',
        #         'managed': True,
        #     },
        # ),
        # migrations.AddField(
        #     model_name='planmapa',
        #     name='componente',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zonas.componente'),
        # ),
        # migrations.AddField(
        #     model_name='planmapa',
        #     name='fecha_updated',
        #     field=models.DateField(blank=True, default=datetime.date.today),
        # ),
        # migrations.AddField(
        #     model_name='planmapa',
        #     name='plan',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapas', to='zonas.plan'),
        # ),
        # migrations.AddField(
        #     model_name='planmapa',
        #     name='plan_etapa',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zonas.planetapa'),
        # ),
    ]
