# Generated by Django 3.2.12 on 2022-08-10 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0045_auto_20220810_1340'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='planmapa',
            name='fecha_updated',
            field=models.DateField(default=datetime.date.today, blank=True),
        ),
    ]
