"""
Django settings for SistemaUrbano project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
import sys

sys.path.append('/home/zhyper/Django-Projects/SistemaUrbanoProject')




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a+t&d4y!se2r*_^3)n1h+x=lv!p%iyd#gu7^&bf5li1^aw^4a)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS=['*']

CORS_ORIGIN_ALLOW_ALL = True


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    #'tinymce',
    #'froala_editor',
    'django_summernote',
    'mathfilters',
    'django_social_share',
    #LOCALS
    'auth_sys_urbano',
    'world',
    'portal',
    'zonas',
    'planes',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_urbano.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'world.context_processors.get_current_year_to_context',
                'world.context_processors.get_Website_Name',
                'zonas.context_proccesors.get_etapas_plan_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_urbano.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {

    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        #'ENGINE': 'django.db.backends.postgresql_psycopg2',
        #'NAME': 'pgt41zre_junio_2022',
        'NAME': 'pg41zre_junio_2021',
        'USER': 'postgres',
        #"PASSWORD":"Catalogacion2020",
        "PASSWORD":"Zhyper*332011",
        "HOST":"localhost",
        # "PORT":"5433",
        "PORT":"5432",
        'OPTIONS': {
        'options': '-c search_path=public,zre41'
    },
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR,'static')

STATICFILES_DIRS = (os.path.join(BASE_DIR, "sistema_urbano/static"),)


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# USE_X_FORWARDED_HOST = True
# FORCE_SCRIPT_NAME = '/someuri'
# STATIC_SUFFIX = '/static/'
# STATIC_URL = FORCE_SCRIPT_NAME + STATIC_SUFFIX
# MEDIA_SUFFIX = '/media/'
# MEDIA_URL = FORCE_SCRIPT_NAME + MEDIA_SUFFIX



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#summnernote
SUMMERNOTE_THEME = 'bs4'
SUMMERNOTE_CONFIG = {
    'lang': 'es-ES',
}

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
 
 
}

X_FRAME_OPTIONS = 'SAMEORIGIN'

EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.gmail.com"
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER=""
EMAIL_HOST_PASSWORD=""


DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880