# Generated by Django 3.2.12 on 2022-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapaweb',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
