# Generated by Django 3.2.12 on 2022-03-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gisbasezonaszre',
            options={},
        ),
    ]
