# Generated by Django 3.2.12 on 2022-03-28 17:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_rename_wkb_geometry_gisbasezonaszre_mpoly'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisBaseZonasZreDjango',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'gis_base_zonas_zre_django',
                'managed': False,
            },
        ),
    ]
