# Generated by Django 3.2.12 on 2022-03-28 19:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_comarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comarca',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
