# Generated by Django 3.2.12 on 2022-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_tzona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tzona',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tzona',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tzona',
            name='zoom',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
