# Generated by Django 3.2.12 on 2022-06-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_auto_20220407_1200'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tzona',
            table='t_zona',
        ),
    ]
