# Generated by Django 3.2.12 on 2022-06-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_alter_tzona_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tzona',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='tzona',
            table='t_zona',
        ),
    ]
