# Generated by Django 3.2.12 on 2022-06-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_auto_20220620_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tzona',
            options={},
        ),
        migrations.AlterField(
            model_name='tzona',
            name='codigo_zona',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tzona',
            name='distrito',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tzona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tzona',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tzona',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tzona',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tzona',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tzona',
            name='observacion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tzona',
            name='zoom',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
