# Generated by Django 3.2.12 on 2022-07-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_auto_20220620_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tzona',
            options={'managed': True},
        ),
    ]
