# Generated by Django 3.2.12 on 2022-09-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0015_tzona_tipo_zre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tzona',
            name='tipo_zre',
            field=models.CharField(choices=[('apma', 'Areas de Peligro Muy Alto'), ('acpa', 'Areas de Conservación y Protección Ambiental')], max_length=15, null=True),
        ),
    ]
