# Generated by Django 3.2.12 on 2022-09-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_alter_tzona_tipo_zre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tzona',
            name='bearing',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tzona',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tzona',
            name='pitch',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
